//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Keeper_WCF_Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookXAuthors = new HashSet<BookXAuthor>();
        }
    
        public int Bookid { get; set; }
        public string Title { get; set; }
        public decimal Price { get; set; }
        public bool Hidden { get; set; }
        public int Stock { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
    
        public virtual ICollection<BookXAuthor> BookXAuthors { get; set; }
    }
}
