//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Keeper_WCF_Service.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookXAuthor
    {
        public int BooksXAuthorsid { get; set; }
        public int Bookid { get; set; }
        public int Authorid { get; set; }
        public bool Hidden { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Book Book { get; set; }
    }
}
